Repository cloudposse/terraform-aws-ecs-web-app, pull requests merged in 2024-08, with the labels that each got.

#285 linux parameters add
  main.tf
  variables.tf
Labels: triage

#284 Fix EFS volume configuration getting discarded
  main.tf
Labels: bugfix

#286 Update .github/settings.yml
  .github/settings.yml
Labels: auto-update, no-release, migration

#287 Update .github/settings.yml
  .github/settings.yml
Labels: auto-update, no-release, migration
